# Move the directory to the second line
format = '$all\[$username:$hostname\] '

[character]
success_symbol = "⬢"

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](bold red)'
disabled = false
